"""
LinkedIn Poster - Playwright Browser Automation
Silver Tier Component
Enhanced with Gold Tier Audit Logging & Error Recovery

Automates LinkedIn posting using Playwright for browser automation.
Based on: Skills/linkedin_poster.md

Features:
- Post text content to LinkedIn
- Support for scheduled posts
- Human-in-the-loop approval integration
- Session persistence for login state

Requirements:
- pip install playwright
- playwright install chromium

Usage:
- Simulation mode (default): Test without actual posting
- Live mode: Requires LinkedIn login via persistent session
"""

import os
import sys
import json
import time
from datetime import datetime
from pathlib import Path

# Add parent directory for imports
sys.path.insert(0, str(Path(__file__).parent.parent))

from utils.audit_logger import (
    get_audit_logger,
    ActionType,
    ApprovalStatus,
    ResultStatus
)

from utils.retry_handler import (
    get_retry_handler,
    get_circuit_breaker,
    get_queue_manager
)

# Configuration
BASE_DIR = Path(__file__).parent.parent
VAULT_DIR = BASE_DIR / "AI_Employee_Vault"

# Actor name for audit logging
ACTOR = "linkedin_poster"

# Initialize audit logger
audit_logger = get_audit_logger()

# Initialize retry handler
retry_handler = get_retry_handler(
    actor=ACTOR,
    circuit_breaker="linkedin_posting"
)
circuit_breaker = get_circuit_breaker("linkedin_posting")
queue_manager = get_queue_manager()

INBOX_LINKEDIN_DIR = VAULT_DIR / "Inbox" / "linkedin"
NEEDS_ACTION_LINKEDIN_DIR = VAULT_DIR / "Needs_Action" / "linkedin"
PENDING_DIR = VAULT_DIR / "Pending_Approval"
APPROVED_DIR = VAULT_DIR / "Approved"
DONE_DIR = VAULT_DIR / "Done"
LOGS_DIR = VAULT_DIR / "Logs"
SESSION_DIR = BASE_DIR / "secrets" / "linkedin_session"

SIMULATION_MODE = os.environ.get("LINKEDIN_SIMULATION", "true").lower() == "true"


def log(message, level="INFO"):
    """Print a timestamped log message."""
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    print(f"[{timestamp}] [{level}] {message}")


def log_to_file(action, details):
    """Log action to daily log file."""
    LOGS_DIR.mkdir(parents=True, exist_ok=True)
    log_file = LOGS_DIR / f"{datetime.now().strftime('%Y-%m-%d')}_linkedin.json"

    entry = {
        "timestamp": datetime.now().isoformat(),
        "action": action,
        "details": details
    }

    logs = []
    if log_file.exists():
        try:
            with open(log_file, "r") as f:
                logs = json.load(f)
        except:
            logs = []

    logs.append(entry)

    with open(log_file, "w") as f:
        json.dump(logs, f, indent=2)


def create_approval_request(content, hashtags=None, schedule_time=None):
    """Create an approval request for a LinkedIn post."""
    start_time = datetime.now()
    PENDING_DIR.mkdir(parents=True, exist_ok=True)

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"LINKEDIN_POST_{timestamp}.md"
    filepath = PENDING_DIR / filename

    hashtags_str = " ".join([f"#{h}" for h in (hashtags or [])])
    schedule_info = schedule_time or "Immediate (upon approval)"

    request_content = f"""---
type: approval_request
request_id: LINKEDIN_{timestamp}
action: post_linkedin
created: {datetime.now().isoformat()}
schedule_time: {schedule_info}
status: pending
priority: medium
---

# LinkedIn Post Approval Request

## Post Content

{content}

## Hashtags

{hashtags_str or "No hashtags specified"}

## Schedule

**Post Time:** {schedule_info}

## Preview

---
{content}

{hashtags_str}
---

## Instructions

**To Approve:** Move this file to `/Approved/` folder

**To Reject:** Move this file to `/Rejected/` folder

---
*Generated by LinkedIn Poster Skill*
*Awaiting human approval*
"""

    with open(filepath, "w") as f:
        f.write(request_content)

    log(f"Created approval request: {filename}")

    # Audit log: approval requested
    audit_logger.log_with_duration(
        action_type=ActionType.APPROVAL_REQUESTED,
        actor=ACTOR,
        target=str(filepath),
        start_time=start_time,
        parameters={
            'content_length': len(content),
            'hashtags': hashtags or [],
            'schedule_time': schedule_info
        },
        approval_status=ApprovalStatus.PENDING,
        result=ResultStatus.SUCCESS
    )

    return filepath


def post_to_linkedin_simulated(content, hashtags=None):
    """Simulate posting to LinkedIn."""
    start_time = datetime.now()
    log("SIMULATION: Would post to LinkedIn")
    log(f"  Content: {content[:50]}...")
    if hashtags:
        log(f"  Hashtags: {hashtags}")

    result = {
        "success": True,
        "post_id": f"sim_post_{datetime.now().strftime('%Y%m%d%H%M%S')}",
        "content_preview": content[:100],
        "posted_at": datetime.now().isoformat(),
        "simulation": True
    }

    log_to_file("post_simulated", result)

    # Audit log: LinkedIn post (simulated)
    audit_logger.log_with_duration(
        action_type=ActionType.LINKEDIN_POST,
        actor=ACTOR,
        target=result["post_id"],
        start_time=start_time,
        parameters={
            'content_length': len(content),
            'hashtags': hashtags or [],
            'simulation': True
        },
        result=ResultStatus.SUCCESS
    )

    return result


def _do_post_to_linkedin_live(content, hashtags, full_content, start_time):
    """Internal LinkedIn live posting logic (called by retry handler)."""
    from playwright.sync_api import sync_playwright

    with sync_playwright() as p:
        # Use persistent context to maintain login session
        SESSION_DIR.mkdir(parents=True, exist_ok=True)

        browser = p.chromium.launch_persistent_context(
            str(SESSION_DIR),
            headless=False,  # Show browser for debugging
            slow_mo=500  # Slow down for visibility
        )

        page = browser.pages[0] if browser.pages else browser.new_page()

        # Navigate to LinkedIn
        log("Navigating to LinkedIn...")
        page.goto("https://www.linkedin.com/feed/")

        # Wait for page to load
        page.wait_for_load_state("networkidle")

        # Check if logged in
        if "login" in page.url.lower() or "checkpoint" in page.url.lower():
            log("Not logged in. Please log in manually and run again.", "WARN")
            log("Session will be saved for future use.")
            input("Press Enter after logging in...")
            page.wait_for_load_state("networkidle")

        # Find the post input
        log("Looking for post input...")

        # Click on the post input to open the modal
        post_button = page.locator('button:has-text("Start a post")')
        if post_button.count() > 0:
            post_button.first.click()
            time.sleep(1)

        # Find the text editor
        editor = page.locator('[role="textbox"]').first
        if editor:
            log("Entering post content...")
            editor.fill(full_content)
            time.sleep(1)

            # Click Post button
            post_btn = page.locator('button:has-text("Post")')
            if post_btn.count() > 0:
                post_btn.first.click()
                log("Post button clicked!")
                time.sleep(3)

                result = {
                    "success": True,
                    "post_id": f"linkedin_{datetime.now().strftime('%Y%m%d%H%M%S')}",
                    "content_preview": content[:100],
                    "posted_at": datetime.now().isoformat()
                }

                log_to_file("post_live", result)

                # Audit log: LinkedIn post (live)
                audit_logger.log_with_duration(
                    action_type=ActionType.LINKEDIN_POST,
                    actor=ACTOR,
                    target=result["post_id"],
                    start_time=start_time,
                    parameters={
                        'content_length': len(content),
                        'hashtags': hashtags or [],
                        'simulation': False
                    },
                    result=ResultStatus.SUCCESS
                )

                browser.close()
                return result

        browser.close()
        raise Exception("Could not find post elements")


def post_to_linkedin_live(content, hashtags=None):
    """Post to LinkedIn using Playwright (with retry handling)."""
    start_time = datetime.now()

    try:
        from playwright.sync_api import sync_playwright
    except ImportError:
        log("Playwright not installed. Run: pip install playwright && playwright install chromium", "ERROR")
        audit_logger.log_error(
            actor=ACTOR,
            target="linkedin_live",
            error_message="Playwright not installed",
            error_type="ImportError"
        )
        return {"success": False, "error": "Playwright not installed"}

    full_content = content
    if hashtags:
        full_content += "\n\n" + " ".join([f"#{h}" for h in hashtags])

    log("Starting LinkedIn posting via Playwright...")

    # Check circuit breaker
    if not circuit_breaker.can_execute():
        log("CIRCUIT OPEN: Skipping LinkedIn posting", "WARNING")
        audit_logger.log(
            action_type=ActionType.WARNING_RAISED,
            actor=ACTOR,
            target="linkedin_live",
            parameters={'reason': 'circuit_breaker_open'},
            result=ResultStatus.FAILURE
        )
        return {"success": False, "error": "Circuit breaker open"}

    try:
        # Execute with retry handling
        result = retry_handler.execute(
            _do_post_to_linkedin_live,
            content,
            hashtags,
            full_content,
            start_time,
            task_id=f"linkedin_post_{datetime.now().strftime('%Y%m%d%H%M%S')}",
            task_type="linkedin_posting"
        )
        circuit_breaker.record_success()
        return result

    except Exception as e:
        log(f"Error posting to LinkedIn: {e}", "ERROR")
        circuit_breaker.record_failure(e)
        audit_logger.log_error(
            actor=ACTOR,
            target="linkedin_live",
            error_message=str(e),
            error_type=type(e).__name__,
            parameters={'retries_exhausted': True}
        )
        return {"success": False, "error": str(e)}


def post_to_linkedin(content, hashtags=None, require_approval=True):
    """Main posting function with approval workflow."""
    log("Starting LinkedIn post workflow...")

    if require_approval:
        # Create approval request
        approval_file = create_approval_request(content, hashtags)
        log(f"Post requires approval. Request created at: {approval_file}")
        return {
            "status": "pending_approval",
            "approval_file": str(approval_file)
        }

    # Direct posting (for approved posts)
    if SIMULATION_MODE:
        return post_to_linkedin_simulated(content, hashtags)
    else:
        return post_to_linkedin_live(content, hashtags)


def process_approved_posts():
    """Process any approved LinkedIn posts in the Approved folder."""
    APPROVED_DIR.mkdir(parents=True, exist_ok=True)

    approved_posts = [
        f for f in APPROVED_DIR.iterdir()
        if f.is_file() and f.name.startswith("LINKEDIN_") and f.suffix == ".md"
    ]

    if not approved_posts:
        log("No approved LinkedIn posts found")
        return []

    results = []
    for post_file in approved_posts:
        start_time = datetime.now()
        log(f"Processing approved post: {post_file.name}")

        # Audit log: approval granted
        audit_logger.log(
            action_type=ActionType.APPROVAL_GRANTED,
            actor=ACTOR,
            target=post_file.name,
            parameters={'source_folder': 'Approved'},
            approval_status=ApprovalStatus.APPROVED,
            result=ResultStatus.SUCCESS
        )

        # Parse the post content
        with open(post_file, "r") as f:
            content = f.read()

        # Extract post content from between "## Post Content" and "## Hashtags"
        post_content = ""
        hashtags = []

        if "## Post Content" in content:
            start = content.find("## Post Content") + len("## Post Content")
            end = content.find("## Hashtags")
            if end > start:
                post_content = content[start:end].strip()

        # Post it
        result = post_to_linkedin(post_content, hashtags, require_approval=False)
        results.append(result)

        # Move to Done
        done_path = DONE_DIR / post_file.name
        post_file.rename(done_path)

        # Add completion record
        with open(done_path, "a") as f:
            f.write(f"\n\n---\n\n## Execution Record\n\n")
            f.write(f"**Executed At:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
            f.write(f"**Result:** {json.dumps(result)}\n")

        log(f"Post completed and moved to Done")

        # Audit log: task completed
        audit_logger.log_with_duration(
            action_type=ActionType.TASK_COMPLETED,
            actor=ACTOR,
            target=post_file.name,
            start_time=start_time,
            parameters={
                'destination': 'Done',
                'post_result': result.get('success', False)
            },
            approval_status=ApprovalStatus.APPROVED,
            result=ResultStatus.SUCCESS if result.get('success') else ResultStatus.FAILURE
        )

    return results


def generate_business_post():
    """Generate a sample business post for testing."""
    posts = [
        {
            "content": "Excited to share our latest AI automation project! Building the future of autonomous business operations.",
            "hashtags": ["AI", "Automation", "Innovation", "Tech"]
        },
        {
            "content": "Productivity tip: Automate your repetitive tasks and focus on what matters most. Here's how we're doing it with AI agents.",
            "hashtags": ["Productivity", "AI", "BusinessTips"]
        },
        {
            "content": "Just completed another milestone in our digital transformation journey. The future is autonomous!",
            "hashtags": ["DigitalTransformation", "AI", "FutureOfWork"]
        }
    ]

    import random
    return random.choice(posts)


def run_linkedin_poster():
    """Main LinkedIn poster interface."""
    print("=" * 60)
    print("Silver Tier - LinkedIn Poster")
    print("With Gold Tier Audit Logging")
    print("=" * 60)
    print(f"Simulation Mode: {SIMULATION_MODE}")
    print(f"Pending Approval: {PENDING_DIR}")
    print(f"Approved: {APPROVED_DIR}")
    print("=" * 60)
    print()

    # Audit log: system started
    audit_logger.log(
        action_type=ActionType.SYSTEM_STARTED,
        actor=ACTOR,
        target="linkedin_poster",
        parameters={
            'simulation_mode': SIMULATION_MODE,
            'pending_dir': str(PENDING_DIR),
            'approved_dir': str(APPROVED_DIR)
        },
        result=ResultStatus.SUCCESS
    )

    # Ensure directories exist
    for dir_path in [INBOX_LINKEDIN_DIR, NEEDS_ACTION_LINKEDIN_DIR,
                     PENDING_DIR, APPROVED_DIR, DONE_DIR, LOGS_DIR]:
        dir_path.mkdir(parents=True, exist_ok=True)

    # Check for approved posts first
    log("Checking for approved LinkedIn posts...")
    results = process_approved_posts()

    if results:
        print()
        print("=" * 60)
        print("POSTING SUMMARY")
        print("=" * 60)
        for i, result in enumerate(results, 1):
            print(f"{i}. {result}")

        # Circuit breaker status
        cb_state = circuit_breaker.get_state()
        print(f"Circuit State:   {cb_state['state']}")

        # Retry queue status
        queue_stats = queue_manager.get_queue_stats()
        if queue_stats['total_tasks'] > 0:
            print(f"Retry Queue:     {queue_stats['total_tasks']} tasks pending")

        print("=" * 60)
    else:
        # Generate a sample post for demonstration
        log("No approved posts. Generating sample post for approval...")
        sample = generate_business_post()
        create_approval_request(sample["content"], sample["hashtags"])
        print()
        log("Sample post created. Move it to /Approved to post.")

    # Audit log: system stopped
    audit_logger.log(
        action_type=ActionType.SYSTEM_STOPPED,
        actor=ACTOR,
        target="linkedin_poster",
        parameters={
            'posts_processed': len(results),
            'successful': sum(1 for r in results if r.get('success', False))
        },
        result=ResultStatus.SUCCESS
    )
    audit_logger.flush()


if __name__ == "__main__":
    if "--process-approved" in sys.argv:
        # Just process approved posts
        process_approved_posts()
    elif "--generate" in sys.argv:
        # Generate a sample post
        sample = generate_business_post()
        create_approval_request(sample["content"], sample["hashtags"])
    else:
        run_linkedin_poster()
