#!/bin/bash
# Platinum Tier - VM Quick Setup Script
# AI Employee Hackathon
#
# Usage: ./setup-vm.sh
#
# This script:
# 1. Creates required directories
# 2. Generates SSH key for Git
# 3. Creates .env file
# 4. Prompts for vault repo URL
# 5. Clones vault
# 6. Builds Docker image

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log() { echo -e "${GREEN}[✓]${NC} $1"; }
warn() { echo -e "${YELLOW}[!]${NC} $1"; }
error() { echo -e "${RED}[✗]${NC} $1"; exit 1; }
info() { echo -e "${BLUE}[i]${NC} $1"; }

echo ""
echo "=========================================="
echo "  AI Employee - Cloud VM Setup"
echo "  Platinum Tier"
echo "=========================================="
echo ""

# Check if running as root
if [ "$EUID" -eq 0 ]; then
    error "Don't run as root. Run as your regular user."
fi

# Check Docker
if ! command -v docker &> /dev/null; then
    warn "Docker not found. Installing..."
    curl -fsSL https://get.docker.com | sudo sh
    sudo usermod -aG docker $USER
    warn "Docker installed. Please logout and login, then run this script again."
    exit 0
fi

# Check docker compose
if ! docker compose version &> /dev/null; then
    warn "Docker Compose not found. Installing..."
    sudo apt update && sudo apt install -y docker-compose-plugin
fi

log "Docker and Docker Compose are installed"

# Setup directories
BASE_DIR="$HOME/ai-employee"
SSH_DIR="$BASE_DIR/ssh"
VAULT_DIR="$BASE_DIR/vault"
LOGS_DIR="$BASE_DIR/logs"

info "Setting up directories in $BASE_DIR"
mkdir -p "$SSH_DIR" "$VAULT_DIR" "$LOGS_DIR"
log "Directories created"

# Generate SSH key if not exists
if [ ! -f "$SSH_DIR/id_ed25519" ]; then
    info "Generating SSH key for Git..."
    ssh-keygen -t ed25519 -C "ai-employee-cloud" -f "$SSH_DIR/id_ed25519" -N ""
    log "SSH key generated"
else
    log "SSH key already exists"
fi

echo ""
echo "=========================================="
echo "  IMPORTANT: Add this SSH key to GitHub"
echo "=========================================="
echo ""
cat "$SSH_DIR/id_ed25519.pub"
echo ""
echo "1. Go to: https://github.com/settings/keys"
echo "2. Click 'New SSH key'"
echo "3. Paste the key above"
echo "4. Click 'Add SSH key'"
echo ""
read -p "Press Enter after adding the key to GitHub..."

# Test SSH connection
info "Testing GitHub SSH connection..."
if ssh -T -o StrictHostKeyChecking=accept-new git@github.com 2>&1 | grep -q "successfully authenticated"; then
    log "GitHub SSH connection successful"
else
    warn "GitHub connection test inconclusive. Continuing..."
fi

# Get vault repo URL
echo ""
read -p "Enter your vault Git repo URL (e.g., git@github.com:user/vault.git): " VAULT_REPO

if [ -z "$VAULT_REPO" ]; then
    error "Vault repo URL is required"
fi

# Clone vault
if [ ! -d "$VAULT_DIR/.git" ]; then
    info "Cloning vault repository..."

    # Setup SSH for git
    export GIT_SSH_COMMAND="ssh -i $SSH_DIR/id_ed25519 -o StrictHostKeyChecking=accept-new"

    git clone "$VAULT_REPO" "$VAULT_DIR"
    log "Vault cloned successfully"
else
    log "Vault already exists"
fi

# Get deploy directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEPLOY_DIR="$SCRIPT_DIR"

# Create .env file
if [ ! -f "$DEPLOY_DIR/.env" ]; then
    info "Creating .env configuration..."
    cat > "$DEPLOY_DIR/.env" << EOF
# AI Employee Cloud Agent Configuration
# Generated by setup-vm.sh on $(date)

# Paths
VAULT_PATH=$VAULT_DIR
SSH_PATH=$SSH_DIR
LOGS_PATH=$LOGS_DIR

# Git settings
GIT_USER_NAME=AI Employee Cloud Agent
GIT_USER_EMAIL=cloud-agent@aiemployee.local
VAULT_SYNC_BRANCH=main

# Timing
SYNC_INTERVAL=60
AGENT_INTERVAL=30

# Timezone
TZ=UTC
EOF
    log ".env file created"
else
    log ".env file already exists"
fi

# Build Docker image
echo ""
info "Building Docker image..."
cd "$DEPLOY_DIR"
docker compose build
log "Docker image built"

# Done
echo ""
echo "=========================================="
echo "  Setup Complete!"
echo "=========================================="
echo ""
echo "To start the AI Employee Cloud Agent:"
echo ""
echo "  cd $DEPLOY_DIR"
echo "  docker compose up -d"
echo ""
echo "To view logs:"
echo "  docker compose logs -f"
echo ""
echo "To check status:"
echo "  docker compose ps"
echo ""
echo "To stop:"
echo "  docker compose down"
echo ""
log "Setup finished successfully!"
